### ISSUE TITLE
When I tried to reproduce the project environment with $ conda env create -f environment/gpu-env.yml encountered some problems

### ISSUE THREAD

**Issue by cmciris** [JannerM/mbpo#1]
Failed to build mujoco-py
ERROR: flask 1.1.1 has requirement Werkzeug>=0.15, but you'll have werkzeug 0.14.1 which is incompatible.
ERROR: awscli 1.16.67 has requirement PyYAML<=3.13,>=3.10, but you'll have pyyaml 4.2b4 which is incompatible.

**Comment by cmciris** [comment]
Maybe it need to clearly specify the version of flask and modify version of awscli/PyYAML in requirements.txt

**Comment by JannerM** [comment]
Thanks for the heads-up. The version conflicts should be fixed as of commit 3f52a337b4d3e6732635cd37e24c81fab946db57. (`awscli` is not actually necessary for this code, since right now only running locally is supported.)
