### ISSUE TITLE
mujoco-py checkpoint does not exist

### ISSUE THREAD

**Issue by IcarusWizard** [JannerM/mbpo#10]
https://github.com/JannerM/mbpo/blob/39365f230292a452f0d77d1ad4f2a1795d311052/environment/requirements.txt#L51

It seems `mujoco-py` does not have checkpoint 435d2143abe04fe4648c6c0c1b848bf1fc06b73b anymore. Change this line to `mujoco-py==1.50.1.68` can solve the problem.

**Comment by JannerM** [comment]
Thanks for pointing this out! This is fixed as of [this commit](https://github.com/JannerM/mbpo/commit/49587a1b0b4e91f8068009e0727c71bc68d904f2). 

There is an issue with GPU compilation for `mujoco-py==1.50.1.68`, so I am installing from [my fork](https://github.com/JannerM/mujoco-py/tree/v1.50.1.68) which makes a minimal change to fix this issue.
