### ISSUE TITLE
Observation of the mujoco env

### ISSUE THREAD

**Issue by Shunichi09** [JannerM/mbpo#12]
Hi !!
Thank you for sharing your great research and codes.

I have a question about the mujoco environments about your experiments.
In the paper, your method were compared with the PETS, which needs the states to calculate the reward in off-line, although your method does not need that states.
I checked your codes and your environments, but you did not use the states which are needed to calculate the rewards in off-line. How did you run the PETS  which assume that we can observe the states to calculate the rewards in off-line??  (e.g. we will use get_body_com("torso") to calculate the reward in the Antenv. )

Thank you for your help.

https://github.com/JannerM/mbpo/blob/39365f230292a452f0d77d1ad4f2a1795d311052/mbpo/env/ant.py#L31-L36

**Comment by JannerM** [comment]
Yeah, some of the baselines we compared to require full observability or other additions to the observation. In these cases, we just ran the baseline with the appropriate modifications to the environment to give it a fair shot. 

In the particular case of ant, the PETS authors kindly gave us a version of the environment compatible with their code. Here are two gists with the [environment](https://gist.github.com/JannerM/c1245cef9300b0c11fd50a4fd01e9fa5) and the corresponding [config file](https://gist.github.com/JannerM/ad78c1015b99102588f45b8a91a81e89). (These should be placed [here](https://github.com/kchua/handful-of-trials/tree/master/dmbrl/env) and [here](https://github.com/kchua/handful-of-trials/tree/master/dmbrl/config) in the PETS repo, respectively.)

**Comment by Shunichi09** [comment]
I really appreciate your quick response and the codes.
I understood your experimental conditions. Thank you for your help!!
