### ISSUE TITLE
[question] specifying a custom log directory

### ISSUE THREAD

**Issue by samuelstanton** [JannerM/mbpo#13]
I'd like to specify my own log directory to dump the ray logs into, but `mbpo run_local` doesn't seem to have a `--log-dir` flag enabled. It looks like this is set manually in the `config` files right now, but I'd like to be able to easily set the directory in the launch command. Any suggestions?

**Comment by JannerM** [comment]
[This commit](https://github.com/JannerM/mbpo/commit/adcd20a5492c9ea45ea502bdfd759318949d99c5) adds support for specifying a log directory by command line, eg:

```
mbpo run_local examples.development \
        --config=examples.config.ant.0 \
        --gpus=1 \
        --trial-gpus=1 \
        --log-dir /path/to/log-dir \
```

If you do not use the `--log-dir` flag, it will revert to that specified in the [config file](https://github.com/JannerM/mbpo/blob/master/examples/config/ant/0.py#L7).

**Comment by samuelstanton** [comment]
Awesome! Thanks!
