### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by dingchenghu** [JannerM/mbpo#4]
```
mbpo run_local examples.development --config=examples.config.halfcheetah.0 \
	--checkpoint-frequency=1000 --gpus=1 --trial-gpus=1
```

How to run the code? The command seems not working

Thanks!

**Comment by JannerM** [comment]
Could you post the error you get when you run that command?

**Comment by dingchenghu** [comment]
It says `mbpo: command not found`

Thank you

**Comment by JannerM** [comment]
Check out the [installation](https://github.com/JannerM/mbpo#installation) section of the README. It sounds like you might be missing the last command: `pip install -e .`

If you run those commands and it still doesn't work, let me know.

**Comment by dingchenghu** [comment]
Yes, it works after running `pip install -e .`

Thank you so much!
