### ISSUE TITLE
Viskit Installation Problem

### ISSUE THREAD

**Issue by dingchenghu** [JannerM/mbpo#5]
I met this problem while running `pip install -e viskit`

```
(mbpo) dingcheng@dingcheng-GP63-Leopard-8RE:~/Documents/mbpo$ pip install -e viskit
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/dingcheng/Documents/mbpo/viskit
```

Any idea why that would happen? Thanks

**Comment by JannerM** [comment]
It sounds like your `viskit` folder might be empty. Did you include the `--recursive` flag when cloning the repo? (See the first command in the [installation instructions](https://github.com/JannerM/mbpo#installation) in the README.)
