### ISSUE TITLE
Runtime error on Walker2D

### ISSUE THREAD

**Issue by roosephu** [JannerM/mbpo#6]
Hi,

Thanks for releasing the code!

I'd like to run MBPO on Walker2D. It seems that it threw an error about the argument `model_pool_size` (https://github.com/JannerM/mbpo/blob/master/examples/config/walker2d/0.py#L25), which seems to be deprecated (https://github.com/JannerM/mbpo/blob/master/mbpo/algorithms/mbpo.py#L107).

**Comment by JannerM** [comment]
Good catch! This has been fixed in commit 56b50792a5e87a25eb99bdc91c02e11612195522.

**Comment by roosephu** [comment]
Thanks!
